# Generated by Django 5.2.7 on 2025-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('experience', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
