# Generated by Django 5.2.7 on 2025-11-20 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-submitted_at'], 'verbose_name': '人員', 'verbose_name_plural': '人員列表'},
        ),
        migrations.AddField(
            model_name='person',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='是否審核通過'),
        ),
        migrations.AddField(
            model_name='person',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交時間'),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='經驗年資'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=20, verbose_name='職位'),
        ),
    ]
