# Generated by Django 5.2.7 on 2025-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_person_options_person_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, unique=True, verbose_name='Google Place ID')),
                ('name', models.CharField(max_length=200, verbose_name='店名')),
                ('address', models.CharField(max_length=300, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='經度')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='評分')),
                ('opening_hours', models.TextField(verbose_name='營業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '奶茶店',
                'verbose_name_plural': '奶茶店列表',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
