# Generated by Django 5.2.7 on 2025-11-26 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_teashop_delete_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='飲料名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('milk_type', models.CharField(choices=[('creamer', '奶精'), ('fresh_milk', '鮮奶'), ('both', '兩者皆有'), ('none', '無奶類')], default='none', max_length=20, verbose_name='使用奶類')),
                ('has_small', models.BooleanField(default=False, verbose_name='有小杯')),
                ('price_small', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='小杯價格')),
                ('has_medium', models.BooleanField(default=False, verbose_name='有中杯')),
                ('price_medium', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='中杯價格')),
                ('has_large', models.BooleanField(default=False, verbose_name='有大杯')),
                ('price_large', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='大杯價格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('tea_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='polls.teashop', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '飲料品項',
                'verbose_name_plural': '飲料品項列表',
                'ordering': ['tea_shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_type', models.CharField(choices=[('shop', '店家'), ('drink', '飲料')], max_length=10, verbose_name='收藏類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='polls.drink', verbose_name='收藏的飲料')),
                ('tea_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='polls.teashop', verbose_name='收藏的店家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏列表',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tea_shop', 'drink')},
            },
        ),
    ]
