# Generated by Django 5.2.7 on 2025-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_drink_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='milk_type',
            field=models.CharField(choices=[('creamer', '奶精'), ('fresh_milk', '鮮奶')], default='none', max_length=20, verbose_name='使用奶類'),
        ),
    ]
