# Generated by Django 5.2.7 on 2025-12-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_drink_milk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
    ]
