# Generated by Django 5.2.7 on 2025-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_favorite_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='tea_type',
            field=models.CharField(blank=True, choices=[('black_tea', '紅茶'), ('green_tea', '綠茶'), ('oolong_tea', '烏龍茶'), ('blue_tea', '青茶'), ('matcha', '抹茶')], max_length=20, null=True, verbose_name='茶類'),
        ),
        migrations.AddField(
            model_name='drink',
            name='topping',
            field=models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, null=True, verbose_name='配料'),
        ),
    ]
