# Generated by Django 5.2.7 on 2025-12-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_drink_tea_type_drink_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='milk_type',
            field=models.CharField(blank=True, choices=[('creamer', '奶精'), ('fresh_milk', '鮮奶')], max_length=20, null=True, verbose_name='使用奶類'),
        ),
    ]
