# Generated by Django 5.2.7 on 2025-12-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_drink_milk_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='has_small',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='price_small',
        ),
        migrations.AlterField(
            model_name='drink',
            name='tea_type',
            field=models.CharField(blank=True, choices=[('black_tea', '紅茶'), ('green_tea', '綠茶'), ('oolong_tea', '烏龍茶'), ('blue_tea', '青茶'), ('matcha', '抹茶'), ('tieguanyin', '鐵觀音'), ('barley_tea', '麥茶'), ('season', '四季春'), ('jasmine', '茉莉花茶'), ('pu_erh', '普洱茶'), ('other', '其他')], max_length=20, null=True, verbose_name='茶類'),
        ),
    ]
